api_keys:
  groq_api_key: ${GROQ_API_KEY}
  tavily_api_key: ${TAVILY_API_KEY}

model_settings:
  allowed_model_names:
    - "openai/gpt-oss-120b"
    - "llama-3.3-70b-versatile"
    - "deepseek-r1-distill-llama-70b"
  model_temperature: 0
  top_k: 10
  debug_key: 9999

tavily_config:
  max_results: 3

urls_and_ports:
  backend_host: "0.0.0.0"
  backend_port: 8000
  frontend_host: "127.0.0.1"
  frontend_port: 8501